### ISSUE TITLE
Adapter stopped working

### ISSUE THREAD

**Issue by Backfire-FF** [TA2k/ioBroker.govee-app#4]
Hi there,

the adapter has suddenly stopped working.

![govee](https://github.com/TA2k/ioBroker.govee-app/assets/66845105/512d16f7-4633-4b1e-b170-1e5fc086c2a4)

Any insights?
Thanks

**Comment by TA2k** [comment]
This adapter is govee-app not govee

**Comment by Backfire-FF** [comment]
Sorry, my bad!
